# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnthropicCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicCodeManager", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeManagerResponse, result)

    def AnthropicConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicConnectionMatching", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionMatchingResponse, result)

    def AnthropicConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicConnectionSplitting", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionSplittingResponse, result)

    def AnthropicImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicImplementationDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AnthropicImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicImportDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AnthropicPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicPackageDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AnthropicRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicRoadmapAgent", llm_response=llm_response, mode="request")
        return typing.cast(types.RoadmapResponse, result)

    def AnthropicTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicTaskFilter", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskFilterResponse, result)

    def AnthropicTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicTechnologyCorrection", llm_response=llm_response, mode="request")
        return typing.cast(types.TechnologyCorrectionResponse, result)

    def AwsCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsCodeManager", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeManagerResponse, result)

    def AwsConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsConnectionMatching", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionMatchingResponse, result)

    def AwsConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsConnectionSplitting", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionSplittingResponse, result)

    def AwsImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsImplementationDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AwsImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsImportDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AwsPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsPackageDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AwsRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsRoadmapAgent", llm_response=llm_response, mode="request")
        return typing.cast(types.RoadmapResponse, result)

    def AwsTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsTaskFilter", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskFilterResponse, result)

    def AwsTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsTechnologyCorrection", llm_response=llm_response, mode="request")
        return typing.cast(types.TechnologyCorrectionResponse, result)

    def AzureAIFoundryCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryCodeManager", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeManagerResponse, result)

    def AzureAIFoundryConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryConnectionMatching", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionMatchingResponse, result)

    def AzureAIFoundryConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryConnectionSplitting", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionSplittingResponse, result)

    def AzureAIFoundryImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryImplementationDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AzureAIFoundryImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryImportDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AzureAIFoundryPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryPackageDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AzureAIFoundryRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryRoadmapAgent", llm_response=llm_response, mode="request")
        return typing.cast(types.RoadmapResponse, result)

    def AzureAIFoundryTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryTaskFilter", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskFilterResponse, result)

    def AzureAIFoundryTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryTechnologyCorrection", llm_response=llm_response, mode="request")
        return typing.cast(types.TechnologyCorrectionResponse, result)

    def AzureCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureCodeManager", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeManagerResponse, result)

    def AzureConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureConnectionMatching", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionMatchingResponse, result)

    def AzureConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureConnectionSplitting", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionSplittingResponse, result)

    def AzureImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureImplementationDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AzureImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureImportDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AzurePackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzurePackageDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def AzureRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureRoadmapAgent", llm_response=llm_response, mode="request")
        return typing.cast(types.RoadmapResponse, result)

    def AzureTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureTaskFilter", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskFilterResponse, result)

    def AzureTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureTechnologyCorrection", llm_response=llm_response, mode="request")
        return typing.cast(types.TechnologyCorrectionResponse, result)

    def ChatGPTCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTCodeManager", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeManagerResponse, result)

    def ChatGPTConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTConnectionMatching", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionMatchingResponse, result)

    def ChatGPTConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTConnectionSplitting", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionSplittingResponse, result)

    def ChatGPTImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTImplementationDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def ChatGPTImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTImportDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def ChatGPTPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTPackageDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def ChatGPTRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTRoadmapAgent", llm_response=llm_response, mode="request")
        return typing.cast(types.RoadmapResponse, result)

    def ChatGPTTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTTaskFilter", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskFilterResponse, result)

    def ChatGPTTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTTechnologyCorrection", llm_response=llm_response, mode="request")
        return typing.cast(types.TechnologyCorrectionResponse, result)

    def GeminiCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiCodeManager", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeManagerResponse, result)

    def GeminiConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiConnectionMatching", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionMatchingResponse, result)

    def GeminiConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiConnectionSplitting", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionSplittingResponse, result)

    def GeminiImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiImplementationDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def GeminiImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiImportDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def GeminiPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiPackageDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def GeminiRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiRoadmapAgent", llm_response=llm_response, mode="request")
        return typing.cast(types.RoadmapResponse, result)

    def GeminiTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiTaskFilter", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskFilterResponse, result)

    def GeminiTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiTechnologyCorrection", llm_response=llm_response, mode="request")
        return typing.cast(types.TechnologyCorrectionResponse, result)

    def OpenRouterCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterCodeManager", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeManagerResponse, result)

    def OpenRouterConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterConnectionMatching", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionMatchingResponse, result)

    def OpenRouterConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterConnectionSplitting", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionSplittingResponse, result)

    def OpenRouterImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterImplementationDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def OpenRouterImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterImportDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def OpenRouterPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterPackageDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def OpenRouterRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterRoadmapAgent", llm_response=llm_response, mode="request")
        return typing.cast(types.RoadmapResponse, result)

    def OpenRouterTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterTaskFilter", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskFilterResponse, result)

    def OpenRouterTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterTechnologyCorrection", llm_response=llm_response, mode="request")
        return typing.cast(types.TechnologyCorrectionResponse, result)

    def VertexAICodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAICodeManager", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeManagerResponse, result)

    def VertexAIConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIConnectionMatching", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionMatchingResponse, result)

    def VertexAIConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIConnectionSplitting", llm_response=llm_response, mode="request")
        return typing.cast(types.ConnectionSplittingResponse, result)

    def VertexAIImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIImplementationDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def VertexAIImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIImportDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def VertexAIPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIPackageDiscovery", llm_response=llm_response, mode="request")
        return typing.cast(types.CrossIndexingResponse, result)

    def VertexAIRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIRoadmapAgent", llm_response=llm_response, mode="request")
        return typing.cast(types.RoadmapResponse, result)

    def VertexAITaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAITaskFilter", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskFilterResponse, result)

    def VertexAITechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAITechnologyCorrection", llm_response=llm_response, mode="request")
        return typing.cast(types.TechnologyCorrectionResponse, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnthropicCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicCodeManager", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeManagerResponse, result)

    def AnthropicConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicConnectionMatching", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionMatchingResponse, result)

    def AnthropicConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicConnectionSplitting", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionSplittingResponse, result)

    def AnthropicImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicImplementationDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AnthropicImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicImportDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AnthropicPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicPackageDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AnthropicRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicRoadmapAgent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoadmapResponse, result)

    def AnthropicTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicTaskFilter", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskFilterResponse, result)

    def AnthropicTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnthropicTechnologyCorrection", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TechnologyCorrectionResponse, result)

    def AwsCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsCodeManager", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeManagerResponse, result)

    def AwsConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsConnectionMatching", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionMatchingResponse, result)

    def AwsConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsConnectionSplitting", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionSplittingResponse, result)

    def AwsImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsImplementationDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AwsImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsImportDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AwsPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsPackageDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AwsRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsRoadmapAgent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoadmapResponse, result)

    def AwsTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsTaskFilter", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskFilterResponse, result)

    def AwsTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AwsTechnologyCorrection", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TechnologyCorrectionResponse, result)

    def AzureAIFoundryCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryCodeManager", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeManagerResponse, result)

    def AzureAIFoundryConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryConnectionMatching", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionMatchingResponse, result)

    def AzureAIFoundryConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryConnectionSplitting", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionSplittingResponse, result)

    def AzureAIFoundryImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryImplementationDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AzureAIFoundryImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryImportDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AzureAIFoundryPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryPackageDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AzureAIFoundryRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryRoadmapAgent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoadmapResponse, result)

    def AzureAIFoundryTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryTaskFilter", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskFilterResponse, result)

    def AzureAIFoundryTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureAIFoundryTechnologyCorrection", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TechnologyCorrectionResponse, result)

    def AzureCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureCodeManager", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeManagerResponse, result)

    def AzureConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureConnectionMatching", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionMatchingResponse, result)

    def AzureConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureConnectionSplitting", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionSplittingResponse, result)

    def AzureImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureImplementationDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AzureImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureImportDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AzurePackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzurePackageDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def AzureRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureRoadmapAgent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoadmapResponse, result)

    def AzureTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureTaskFilter", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskFilterResponse, result)

    def AzureTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AzureTechnologyCorrection", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TechnologyCorrectionResponse, result)

    def ChatGPTCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTCodeManager", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeManagerResponse, result)

    def ChatGPTConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTConnectionMatching", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionMatchingResponse, result)

    def ChatGPTConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTConnectionSplitting", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionSplittingResponse, result)

    def ChatGPTImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTImplementationDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def ChatGPTImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTImportDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def ChatGPTPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTPackageDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def ChatGPTRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTRoadmapAgent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoadmapResponse, result)

    def ChatGPTTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTTaskFilter", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskFilterResponse, result)

    def ChatGPTTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChatGPTTechnologyCorrection", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TechnologyCorrectionResponse, result)

    def GeminiCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiCodeManager", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeManagerResponse, result)

    def GeminiConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiConnectionMatching", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionMatchingResponse, result)

    def GeminiConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiConnectionSplitting", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionSplittingResponse, result)

    def GeminiImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiImplementationDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def GeminiImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiImportDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def GeminiPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiPackageDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def GeminiRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiRoadmapAgent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoadmapResponse, result)

    def GeminiTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiTaskFilter", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskFilterResponse, result)

    def GeminiTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeminiTechnologyCorrection", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TechnologyCorrectionResponse, result)

    def OpenRouterCodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterCodeManager", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeManagerResponse, result)

    def OpenRouterConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterConnectionMatching", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionMatchingResponse, result)

    def OpenRouterConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterConnectionSplitting", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionSplittingResponse, result)

    def OpenRouterImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterImplementationDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def OpenRouterImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterImportDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def OpenRouterPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterPackageDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def OpenRouterRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterRoadmapAgent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoadmapResponse, result)

    def OpenRouterTaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterTaskFilter", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskFilterResponse, result)

    def OpenRouterTechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="OpenRouterTechnologyCorrection", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TechnologyCorrectionResponse, result)

    def VertexAICodeManager(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeManagerResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAICodeManager", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeManagerResponse, result)

    def VertexAIConnectionMatching(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionMatchingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIConnectionMatching", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionMatchingResponse, result)

    def VertexAIConnectionSplitting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConnectionSplittingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIConnectionSplitting", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConnectionSplittingResponse, result)

    def VertexAIImplementationDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIImplementationDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def VertexAIImportDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIImportDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def VertexAIPackageDiscovery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrossIndexingResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIPackageDiscovery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrossIndexingResponse, result)

    def VertexAIRoadmapAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoadmapResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAIRoadmapAgent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoadmapResponse, result)

    def VertexAITaskFilter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskFilterResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAITaskFilter", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskFilterResponse, result)

    def VertexAITechnologyCorrection(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TechnologyCorrectionResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="VertexAITechnologyCorrection", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TechnologyCorrectionResponse, result)

    