# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AddTask": types.AddTask,
    "stream_types.AddTask": stream_types.AddTask,

    "types.BaseCompletionParams": types.BaseCompletionParams,
    "stream_types.BaseCompletionParams": stream_types.BaseCompletionParams,

    "types.ChangeInstruction": types.ChangeInstruction,
    "stream_types.ChangeInstruction": stream_types.ChangeInstruction,

    "types.CodeConnection": types.CodeConnection,
    "stream_types.CodeConnection": stream_types.CodeConnection,

    "types.CodeManagerResponse": types.CodeManagerResponse,
    "stream_types.CodeManagerResponse": stream_types.CodeManagerResponse,

    "types.CodeStorage": types.CodeStorage,
    "stream_types.CodeStorage": stream_types.CodeStorage,

    "types.CodeStorage_CrossIndexing": types.CodeStorage_CrossIndexing,
    "stream_types.CodeStorage_CrossIndexing": stream_types.CodeStorage_CrossIndexing,

    "types.CompletionResponse_CrossIndexing": types.CompletionResponse_CrossIndexing,
    "stream_types.CompletionResponse_CrossIndexing": stream_types.CompletionResponse_CrossIndexing,

    "types.CompletionToolCall": types.CompletionToolCall,
    "stream_types.CompletionToolCall": stream_types.CompletionToolCall,

    "types.CompletionToolCall_CrossIndexing": types.CompletionToolCall_CrossIndexing,
    "stream_types.CompletionToolCall_CrossIndexing": stream_types.CompletionToolCall_CrossIndexing,

    "types.ConnectionDetail": types.ConnectionDetail,
    "stream_types.ConnectionDetail": stream_types.ConnectionDetail,

    "types.ConnectionMatch": types.ConnectionMatch,
    "stream_types.ConnectionMatch": stream_types.ConnectionMatch,

    "types.ConnectionMatchingResponse": types.ConnectionMatchingResponse,
    "stream_types.ConnectionMatchingResponse": stream_types.ConnectionMatchingResponse,

    "types.ConnectionSplittingResponse": types.ConnectionSplittingResponse,
    "stream_types.ConnectionSplittingResponse": stream_types.ConnectionSplittingResponse,

    "types.Contract": types.Contract,
    "stream_types.Contract": stream_types.Contract,

    "types.ContractField": types.ContractField,
    "stream_types.ContractField": stream_types.ContractField,

    "types.CrossIndexingResponse": types.CrossIndexingResponse,
    "stream_types.CrossIndexingResponse": stream_types.CrossIndexingResponse,

    "types.DatabaseParams": types.DatabaseParams,
    "stream_types.DatabaseParams": stream_types.DatabaseParams,

    "types.DatabaseParamsGetBlockDetails": types.DatabaseParamsGetBlockDetails,
    "stream_types.DatabaseParamsGetBlockDetails": stream_types.DatabaseParamsGetBlockDetails,

    "types.DatabaseParamsGetFileByPath": types.DatabaseParamsGetFileByPath,
    "stream_types.DatabaseParamsGetFileByPath": stream_types.DatabaseParamsGetFileByPath,

    "types.DatabaseToolCall": types.DatabaseToolCall,
    "stream_types.DatabaseToolCall": stream_types.DatabaseToolCall,

    "types.DatabaseToolCallSimple": types.DatabaseToolCallSimple,
    "stream_types.DatabaseToolCallSimple": stream_types.DatabaseToolCallSimple,

    "types.DeveloperCompletionParams": types.DeveloperCompletionParams,
    "stream_types.DeveloperCompletionParams": stream_types.DeveloperCompletionParams,

    "types.DeveloperCompletionToolCall": types.DeveloperCompletionToolCall,
    "stream_types.DeveloperCompletionToolCall": stream_types.DeveloperCompletionToolCall,

    "types.DeveloperPromptParams": types.DeveloperPromptParams,
    "stream_types.DeveloperPromptParams": stream_types.DeveloperPromptParams,

    "types.DeveloperResponse": types.DeveloperResponse,
    "stream_types.DeveloperResponse": stream_types.DeveloperResponse,

    "types.DiagnosticsParams": types.DiagnosticsParams,
    "stream_types.DiagnosticsParams": stream_types.DiagnosticsParams,

    "types.DiagnosticsToolCall": types.DiagnosticsToolCall,
    "stream_types.DiagnosticsToolCall": stream_types.DiagnosticsToolCall,

    "types.Edit": types.Edit,
    "stream_types.Edit": stream_types.Edit,

    "types.EditFileParams": types.EditFileParams,
    "stream_types.EditFileParams": stream_types.EditFileParams,

    "types.EditFileToolCall": types.EditFileToolCall,
    "stream_types.EditFileToolCall": stream_types.EditFileToolCall,

    "types.FileChange": types.FileChange,
    "stream_types.FileChange": stream_types.FileChange,

    "types.ListFilesParams": types.ListFilesParams,
    "stream_types.ListFilesParams": stream_types.ListFilesParams,

    "types.ListFilesParamsWithoutProjectName": types.ListFilesParamsWithoutProjectName,
    "stream_types.ListFilesParamsWithoutProjectName": stream_types.ListFilesParamsWithoutProjectName,

    "types.ListFilesToolCall": types.ListFilesToolCall,
    "stream_types.ListFilesToolCall": stream_types.ListFilesToolCall,

    "types.ListFilesToolCallSimple": types.ListFilesToolCallSimple,
    "stream_types.ListFilesToolCallSimple": stream_types.ListFilesToolCallSimple,

    "types.ListFilesToolCallWithoutProjectName": types.ListFilesToolCallWithoutProjectName,
    "stream_types.ListFilesToolCallWithoutProjectName": stream_types.ListFilesToolCallWithoutProjectName,

    "types.Project": types.Project,
    "stream_types.Project": stream_types.Project,

    "types.ProjectContext": types.ProjectContext,
    "stream_types.ProjectContext": stream_types.ProjectContext,

    "types.ProjectRoadmap": types.ProjectRoadmap,
    "stream_types.ProjectRoadmap": stream_types.ProjectRoadmap,

    "types.QAEngineerCompletionParams": types.QAEngineerCompletionParams,
    "stream_types.QAEngineerCompletionParams": stream_types.QAEngineerCompletionParams,

    "types.QAEngineerCompletionToolCall": types.QAEngineerCompletionToolCall,
    "stream_types.QAEngineerCompletionToolCall": stream_types.QAEngineerCompletionToolCall,

    "types.QAEngineerFailedTestsParams": types.QAEngineerFailedTestsParams,
    "stream_types.QAEngineerFailedTestsParams": stream_types.QAEngineerFailedTestsParams,

    "types.QAEngineerPromptParams": types.QAEngineerPromptParams,
    "stream_types.QAEngineerPromptParams": stream_types.QAEngineerPromptParams,

    "types.QAEngineerResponse": types.QAEngineerResponse,
    "stream_types.QAEngineerResponse": stream_types.QAEngineerResponse,

    "types.RoadmapCodeStorage": types.RoadmapCodeStorage,
    "stream_types.RoadmapCodeStorage": stream_types.RoadmapCodeStorage,

    "types.RoadmapCompletionParams": types.RoadmapCompletionParams,
    "stream_types.RoadmapCompletionParams": stream_types.RoadmapCompletionParams,

    "types.RoadmapCompletionToolCall": types.RoadmapCompletionToolCall,
    "stream_types.RoadmapCompletionToolCall": stream_types.RoadmapCompletionToolCall,

    "types.RoadmapPromptParams": types.RoadmapPromptParams,
    "stream_types.RoadmapPromptParams": stream_types.RoadmapPromptParams,

    "types.RoadmapResponse": types.RoadmapResponse,
    "stream_types.RoadmapResponse": stream_types.RoadmapResponse,

    "types.RoadmapSutraMemoryParams": types.RoadmapSutraMemoryParams,
    "stream_types.RoadmapSutraMemoryParams": stream_types.RoadmapSutraMemoryParams,

    "types.SearchKeywordParams": types.SearchKeywordParams,
    "stream_types.SearchKeywordParams": stream_types.SearchKeywordParams,

    "types.SearchKeywordParamsWithoutProjectName": types.SearchKeywordParamsWithoutProjectName,
    "stream_types.SearchKeywordParamsWithoutProjectName": stream_types.SearchKeywordParamsWithoutProjectName,

    "types.SearchKeywordToolCall": types.SearchKeywordToolCall,
    "stream_types.SearchKeywordToolCall": stream_types.SearchKeywordToolCall,

    "types.SearchKeywordToolCallSimple": types.SearchKeywordToolCallSimple,
    "stream_types.SearchKeywordToolCallSimple": stream_types.SearchKeywordToolCallSimple,

    "types.SearchKeywordToolCallWithoutProjectName": types.SearchKeywordToolCallWithoutProjectName,
    "stream_types.SearchKeywordToolCallWithoutProjectName": stream_types.SearchKeywordToolCallWithoutProjectName,

    "types.SemanticSearchParams": types.SemanticSearchParams,
    "stream_types.SemanticSearchParams": stream_types.SemanticSearchParams,

    "types.SemanticSearchParamsWithoutProjectName": types.SemanticSearchParamsWithoutProjectName,
    "stream_types.SemanticSearchParamsWithoutProjectName": stream_types.SemanticSearchParamsWithoutProjectName,

    "types.SemanticSearchToolCall": types.SemanticSearchToolCall,
    "stream_types.SemanticSearchToolCall": stream_types.SemanticSearchToolCall,

    "types.SemanticSearchToolCallSimple": types.SemanticSearchToolCallSimple,
    "stream_types.SemanticSearchToolCallSimple": stream_types.SemanticSearchToolCallSimple,

    "types.SemanticSearchToolCallWithoutProjectName": types.SemanticSearchToolCallWithoutProjectName,
    "stream_types.SemanticSearchToolCallWithoutProjectName": stream_types.SemanticSearchToolCallWithoutProjectName,

    "types.SutraMemoryParams": types.SutraMemoryParams,
    "stream_types.SutraMemoryParams": stream_types.SutraMemoryParams,

    "types.SutraMemoryParams_CrossIndexing": types.SutraMemoryParams_CrossIndexing,
    "stream_types.SutraMemoryParams_CrossIndexing": stream_types.SutraMemoryParams_CrossIndexing,

    "types.SystemInfoParams": types.SystemInfoParams,
    "stream_types.SystemInfoParams": stream_types.SystemInfoParams,

    "types.SystemInfo_CrossIndexing": types.SystemInfo_CrossIndexing,
    "stream_types.SystemInfo_CrossIndexing": stream_types.SystemInfo_CrossIndexing,

    "types.TaskFilterResponse": types.TaskFilterResponse,
    "stream_types.TaskFilterResponse": stream_types.TaskFilterResponse,

    "types.TaskOperation": types.TaskOperation,
    "stream_types.TaskOperation": stream_types.TaskOperation,

    "types.TaskOperation_CrossIndexing": types.TaskOperation_CrossIndexing,
    "stream_types.TaskOperation_CrossIndexing": stream_types.TaskOperation_CrossIndexing,

    "types.TechnologyCorrection": types.TechnologyCorrection,
    "stream_types.TechnologyCorrection": stream_types.TechnologyCorrection,

    "types.TechnologyCorrectionResponse": types.TechnologyCorrectionResponse,
    "stream_types.TechnologyCorrectionResponse": stream_types.TechnologyCorrectionResponse,

    "types.TermianlParams": types.TermianlParams,
    "stream_types.TermianlParams": stream_types.TermianlParams,

    "types.TermianlToolCall": types.TermianlToolCall,
    "stream_types.TermianlToolCall": stream_types.TermianlToolCall,

    "types.TracedElement": types.TracedElement,
    "stream_types.TracedElement": stream_types.TracedElement,

    "types.UntracedElement": types.UntracedElement,
    "stream_types.UntracedElement": stream_types.UntracedElement,


    "types.Agent": types.Agent,

    "types.CodeStorageAction": types.CodeStorageAction,

    "types.CodeStorageAction_CrossIndexing": types.CodeStorageAction_CrossIndexing,

    "types.ContractRole": types.ContractRole,

    "types.DatabaseQueryName": types.DatabaseQueryName,

    "types.EditFileMode": types.EditFileMode,

    "types.ElementType": types.ElementType,

    "types.FileOperation": types.FileOperation,

    "types.ImpactLevel": types.ImpactLevel,

    "types.RoadmapCodeStorageAction": types.RoadmapCodeStorageAction,

    "types.Status_CrossIndexing": types.Status_CrossIndexing,

    "types.TaskOperationAction": types.TaskOperationAction,

    "types.TaskOperationAction_CrossIndexing": types.TaskOperationAction_CrossIndexing,

    "types.TaskStatus": types.TaskStatus,

    "types.TechnologyType": types.TechnologyType,

    "types.ToolName": types.ToolName,

}