# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (15)
# #########################################################################

class Agent(str, Enum):
    Roadmap = "Roadmap"
    CrossIndexing = "CrossIndexing"
    Developer = "Developer"
    QAEngineer = "QAEngineer"

class CodeStorageAction(str, Enum):
    Add = "Add"

class CodeStorageAction_CrossIndexing(str, Enum):
    Add = "Add"
    Remove = "Remove"

class DatabaseQueryName(str, Enum):
    GET_FILE_BY_PATH = "GET_FILE_BY_PATH"
    GET_BLOCK_DETAILS = "GET_BLOCK_DETAILS"

class EditFileMode(str, Enum):
    CREATE = "CREATE"
    EDIT = "EDIT"
    OVERWRITE = "OVERWRITE"

class ElementType(str, Enum):
    FUNCTION = "FUNCTION"
    PROPERTY = "PROPERTY"
    VARIABLE = "VARIABLE"
    ATTRIBUTE = "ATTRIBUTE"
    METHOD = "METHOD"
    CLASS = "CLASS"

class FileOperation(str, Enum):
    Create = "Create"
    Modify = "Modify"
    Delete = "Delete"

class ImpactLevel(str, Enum):
    High = "High"
    Medium = "Medium"
    Low = "Low"
    NoImpact = "NoImpact"

class RoadmapCodeStorageAction(str, Enum):
    Add = "Add"
    UpdateTracingStatus = "UpdateTracingStatus"
    MoveToTraced = "MoveToTraced"
    AddToNeedsTracing = "AddToNeedsTracing"
    UpdateCallChainSummary = "UpdateCallChainSummary"

class Status_CrossIndexing(str, Enum):
    Pending = "Pending"
    Current = "Current"
    Completed = "Completed"

class TaskOperationAction(str, Enum):
    Add = "Add"
    Move = "Move"

class TaskOperationAction_CrossIndexing(str, Enum):
    Add = "Add"
    Remove = "Remove"
    Move = "Move"

class TaskStatus(str, Enum):
    PENDING = "PENDING"
    CURRENT = "CURRENT"
    COMPLETED = "COMPLETED"

class TechnologyType(str, Enum):
    HTTP_HTTPS = "HTTP_HTTPS"
    WebSockets = "WebSockets"
    GRPC = "GRPC"
    GraphQL = "GraphQL"
    MessageQueue = "MessageQueue"
    Unknown = "Unknown"

class ToolName(str, Enum):
    Database = "Database"
    DatabaseSimple = "DatabaseSimple"
    SearchKeyword = "SearchKeyword"
    SearchKeywordSimple = "SearchKeywordSimple"
    SearchKeywordWithoutProjectName = "SearchKeywordWithoutProjectName"
    SemanticSearch = "SemanticSearch"
    SemanticSearchSimple = "SemanticSearchSimple"
    ListFilesWithProjectName = "ListFilesWithProjectName"
    ListFilesWithoutProjectName = "ListFilesWithoutProjectName"
    Terminal = "Terminal"
    Completion = "Completion"
    EditFile = "EditFile"
    Diagnostics = "Diagnostics"

# #########################################################################
# Generated classes (70)
# #########################################################################

class AddTask(BaseModel):
    id: int
    description: str

class BaseCompletionParams(BaseModel):
    result: str

class ChangeInstruction(BaseModel):
    description: str
    guidance: typing.Optional[str] = None
    integration_notes: typing.Optional[str] = None

class CodeConnection(BaseModel):
    id: int
    file: str
    start_line: int
    end_line: int
    description: str

class CodeManagerResponse(BaseModel):
    thinking: typing.Optional[str] = None
    connection_code: typing.Optional[typing.List["CodeConnection"]] = None

class CodeStorage(BaseModel):
    action: CodeStorageAction
    id: int
    file: str
    start_line: int
    end_line: int
    description: str

class CodeStorage_CrossIndexing(BaseModel):
    action: CodeStorageAction_CrossIndexing
    id: int
    file: str
    start_line: int
    end_line: int
    description: str

class CompletionResponse_CrossIndexing(BaseModel):
    result: str

class CompletionToolCall(BaseModel):
    tool_name: typing_extensions.Literal['attempt_completion']
    parameters: "BaseCompletionParams"

class CompletionToolCall_CrossIndexing(BaseModel):
    tool_name: typing_extensions.Literal['attempt_completion']
    parameters: "CompletionResponse_CrossIndexing"

class ConnectionDetail(BaseModel):
    snippet_lines: str
    description: str

class ConnectionMatch(BaseModel):
    incoming_id: int
    outgoing_id: int
    match_confidence: str
    match_reason: str

class ConnectionMatchingResponse(BaseModel):
    matches: typing.Optional[typing.List["ConnectionMatch"]] = None

class ConnectionSplittingResponse(BaseModel):
    incoming_connections: typing.Optional[typing.Dict[typing.Union[TechnologyType, str], typing.Dict[str, typing.List["ConnectionDetail"]]]] = None
    outgoing_connections: typing.Optional[typing.Dict[typing.Union[TechnologyType, str], typing.Dict[str, typing.List["ConnectionDetail"]]]] = None
    summary: typing.Optional[str] = None

class CrossIndexingResponse(BaseModel):
    thinking: typing.Optional[str] = None
    tool_call: typing.Optional[typing.Union["ListFilesToolCallWithoutProjectName", "DatabaseToolCall", "SearchKeywordToolCallWithoutProjectName", "CompletionToolCall_CrossIndexing"]] = None
    sutra_memory: "SutraMemoryParams_CrossIndexing"

class DatabaseParams(BaseModel):
    query_name: DatabaseQueryName
    file_path: typing.Optional[str] = None
    start_line: typing.Optional[int] = None
    end_line: typing.Optional[int] = None
    block_id: typing.Optional[str] = None
    fetch_next_chunk: typing.Optional[bool] = None

class DatabaseParamsGetBlockDetails(BaseModel):
    query_name: typing_extensions.Literal['GET_BLOCK_DETAILS']
    block_id: str
    fetch_next_chunk: typing.Optional[bool] = None

class DatabaseParamsGetFileByPath(BaseModel):
    query_name: typing_extensions.Literal['GET_FILE_BY_PATH']
    file_path: str
    start_line: typing.Optional[int] = None
    end_line: typing.Optional[int] = None
    fetch_next_chunk: typing.Optional[bool] = None

class DatabaseToolCall(BaseModel):
    tool_name: typing_extensions.Literal['database']
    parameters: "DatabaseParams"

class DatabaseToolCallSimple(BaseModel):
    tool_name: typing_extensions.Literal['database']
    parameters: typing.Union["DatabaseParamsGetFileByPath", "DatabaseParamsGetBlockDetails"]

class DeveloperCompletionParams(BaseModel):
    give_up: bool
    result: str

class DeveloperCompletionToolCall(BaseModel):
    tool_name: typing_extensions.Literal['attempt_completion']
    parameters: "DeveloperCompletionParams"

class DeveloperPromptParams(BaseModel):
    context: str
    system_info: "SystemInfoParams"

class DeveloperResponse(BaseModel):
    thinking: str
    sutra_memory: "SutraMemoryParams"
    tool_call: typing.Optional[typing.Union["DatabaseToolCallSimple", "SearchKeywordToolCallWithoutProjectName", "SemanticSearchToolCallWithoutProjectName", "ListFilesToolCallWithoutProjectName", "DeveloperCompletionToolCall", "TermianlToolCall", "EditFileToolCall", "DiagnosticsToolCall"]] = None

class DiagnosticsParams(BaseModel):
    path: str

class DiagnosticsToolCall(BaseModel):
    tool_name: typing_extensions.Literal['diagnostics']
    parameters: "DiagnosticsParams"

class Edit(BaseModel):
    old_text: str
    new_text: str
    line_hint: typing.Optional[int] = None

class EditFileParams(BaseModel):
    path: str
    mode: EditFileMode
    content: typing.Optional[str] = None
    edits: typing.Optional[typing.List["Edit"]] = None

class EditFileToolCall(BaseModel):
    tool_name: typing_extensions.Literal['edit_file']
    parameters: "EditFileParams"

class FileChange(BaseModel):
    file_path: str
    operation: FileOperation
    instructions: typing.List["ChangeInstruction"]

class IntegrationContract(BaseModel):
    contract_id: str
    description: str
    related_projects: typing.List[str]
    specifications: str

class ListFilesParamsWithProjectName(BaseModel):
    path: str
    project_name: str
    recursive: typing.Optional[bool] = None
    fetch_next_chunk: typing.Optional[bool] = None

class ListFilesParamsWithoutProjectName(BaseModel):
    path: str
    recursive: typing.Optional[bool] = None
    fetch_next_chunk: typing.Optional[bool] = None

class ListFilesToolCallWithProjectName(BaseModel):
    tool_name: typing_extensions.Literal['list_files']
    parameters: "ListFilesParamsWithProjectName"

class ListFilesToolCallWithoutProjectName(BaseModel):
    tool_name: typing_extensions.Literal['list_files']
    parameters: "ListFilesParamsWithoutProjectName"

class Project(BaseModel):
    name: str
    path: str
    description: str

class ProjectContext(BaseModel):
    projects: typing.List["Project"]

class ProjectExecutionPlan(BaseModel):
    project_name: str
    project_path: str
    impact_level: ImpactLevel
    reasoning: str
    implementation_plan: typing.List[str]
    changes: typing.Optional[typing.List["FileChange"]] = None
    integration_contracts: typing.Optional[typing.List["IntegrationContract"]] = None

class QAEngineerCompletionParams(BaseModel):
    result: str
    failed_tests: typing.Optional[typing.List["QAEngineerFailedTestsParams"]] = None

class QAEngineerCompletionToolCall(BaseModel):
    tool_name: typing_extensions.Literal['attempt_completion']
    parameters: "QAEngineerCompletionParams"

class QAEngineerFailedTestsParams(BaseModel):
    test_name: str
    test_details: str

class QAEngineerPromptParams(BaseModel):
    context: str
    system_info: "SystemInfoParams"

class QAEngineerResponse(BaseModel):
    thinking: str
    sutra_memory: "SutraMemoryParams"
    tool_call: typing.Union["DatabaseToolCallSimple", "SearchKeywordToolCallWithoutProjectName", "SemanticSearchToolCallWithoutProjectName", "ListFilesToolCallWithoutProjectName", "TermianlToolCall", "QAEngineerCompletionToolCall", "EditFileToolCall", "DiagnosticsToolCall"]

class RoadmapCodeStorage(BaseModel):
    action: RoadmapCodeStorageAction
    id: int
    file: str
    start_line: int
    end_line: int
    description: str
    is_traced: typing.Optional[bool] = None
    root_element: typing.Optional["TracedElement"] = None
    needs_tracing: typing.Optional[typing.List["UntracedElement"]] = None
    traced_element: typing.Optional["TracedElement"] = None
    source_element_id: typing.Optional[str] = None
    element_path: typing.Optional[typing.List[str]] = None
    call_chain_summary: typing.Optional[str] = None

class RoadmapCompletionParams(BaseModel):
    projects: typing.List["ProjectExecutionPlan"]
    summary: str

class RoadmapCompletionToolCall(BaseModel):
    tool_name: typing_extensions.Literal['attempt_completion']
    parameters: typing.Union["RoadmapCompletionParams", "BaseCompletionParams"]

class RoadmapPromptParams(BaseModel):
    context: str
    system_info: "SystemInfoParams"
    project_context: "ProjectContext"

class RoadmapResponse(BaseModel):
    thinking: str
    sutra_memory: "RoadmapSutraMemoryParams"
    tool_call: typing.Optional[typing.Union["DatabaseToolCallSimple", "SearchKeywordToolCallWithProjectName", "SemanticSearchToolCallWithProjectName", "ListFilesToolCallWithProjectName", "RoadmapCompletionToolCall"]] = None

class RoadmapSutraMemoryParams(BaseModel):
    add_history: str
    tasks: typing.Optional[typing.List["TaskOperation"]] = None
    code: typing.Optional[typing.List["RoadmapCodeStorage"]] = None

class SearchKeywordParamsWithProjectName(BaseModel):
    project_name: str
    keyword: str
    file_paths: typing.Optional[typing.List[str]] = None
    before_lines: typing.Optional[int] = None
    after_lines: typing.Optional[int] = None
    case_sensitive: typing.Optional[bool] = None
    regex: typing.Optional[bool] = None
    fetch_next_chunk: typing.Optional[bool] = None

class SearchKeywordParamsWithoutProjectName(BaseModel):
    keyword: str
    file_paths: typing.Optional[typing.List[str]] = None
    before_lines: typing.Optional[int] = None
    after_lines: typing.Optional[int] = None
    case_sensitive: typing.Optional[bool] = None
    regex: typing.Optional[bool] = None
    fetch_next_chunk: typing.Optional[bool] = None

class SearchKeywordToolCallWithProjectName(BaseModel):
    tool_name: typing_extensions.Literal['search_keyword']
    parameters: "SearchKeywordParamsWithProjectName"

class SearchKeywordToolCallWithoutProjectName(BaseModel):
    tool_name: typing_extensions.Literal['search_keyword']
    parameters: "SearchKeywordParamsWithoutProjectName"

class SemanticSearchParamsWithProjectName(BaseModel):
    query: str
    project_name: typing.Optional[str] = None
    fetch_next_chunk: typing.Optional[bool] = None

class SemanticSearchParamsWithoutProjectName(BaseModel):
    query: str
    fetch_next_chunk: typing.Optional[bool] = None

class SemanticSearchToolCallWithProjectName(BaseModel):
    tool_name: typing_extensions.Literal['semantic_search']
    parameters: "SemanticSearchParamsWithProjectName"

class SemanticSearchToolCallWithoutProjectName(BaseModel):
    tool_name: typing_extensions.Literal['semantic_search']
    parameters: "SemanticSearchParamsWithoutProjectName"

class SutraMemoryParams(BaseModel):
    add_history: str
    tasks: typing.Optional[typing.List["TaskOperation"]] = None
    code: typing.Optional[typing.List["CodeStorage"]] = None

class SutraMemoryParams_CrossIndexing(BaseModel):
    add_history: str
    tasks: typing.Optional[typing.List["TaskOperation_CrossIndexing"]] = None
    code: typing.Optional[typing.List["CodeStorage_CrossIndexing"]] = None

class SystemInfoParams(BaseModel):
    os: str
    shell: str
    home: str
    current_dir: str

class SystemInfo_CrossIndexing(BaseModel):
    home: str
    current_dir: str

class TaskFilterResponse(BaseModel):
    tasks: typing.List["AddTask"]

class TaskOperation(BaseModel):
    action: TaskOperationAction
    id: int
    to_status: typing.Optional[TaskStatus] = None
    description: typing.Optional[str] = None

class TaskOperation_CrossIndexing(BaseModel):
    action: TaskOperationAction_CrossIndexing
    id: int
    to_status: typing.Optional[Status_CrossIndexing] = None
    description: typing.Optional[str] = None

class TechnologyCorrection(BaseModel):
    original_name: str
    corrected_name: str

class TechnologyCorrectionResponse(BaseModel):
    corrections: typing.Optional[typing.List["TechnologyCorrection"]] = None

class TermianlParams(BaseModel):
    command: str
    cwd: typing.Optional[str] = None

class TermianlToolCall(BaseModel):
    tool_name: typing_extensions.Literal['terminal']
    parameters: "TermianlParams"

class TracedElement(BaseModel):
    id: typing.Optional[str] = None
    name: str
    element_type: ElementType
    start_line: int
    end_line: int
    signature: str
    content: str
    accessed_elements: typing.Optional[typing.List["TracedElement"]] = None
    is_fully_traced: typing.Optional[bool] = None

class UntracedElement(BaseModel):
    id: str
    name: str
    element_type: ElementType
    reason: typing.Optional[str] = None
    accessed_from: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (4)
# #########################################################################


DeveloperToolCall: typing_extensions.TypeAlias = typing.Union["DatabaseToolCallSimple", "SearchKeywordToolCallWithoutProjectName", "SemanticSearchToolCallWithoutProjectName", "ListFilesToolCallWithoutProjectName", "DeveloperCompletionToolCall", "TermianlToolCall", "EditFileToolCall", "DiagnosticsToolCall"]


QAEngineerToolCall: typing_extensions.TypeAlias = typing.Union["DatabaseToolCallSimple", "SearchKeywordToolCallWithoutProjectName", "SemanticSearchToolCallWithoutProjectName", "ListFilesToolCallWithoutProjectName", "TermianlToolCall", "QAEngineerCompletionToolCall", "EditFileToolCall", "DiagnosticsToolCall"]


RoadmapToolCall: typing_extensions.TypeAlias = typing.Union["DatabaseToolCallSimple", "SearchKeywordToolCallWithProjectName", "SemanticSearchToolCallWithProjectName", "ListFilesToolCallWithProjectName", "RoadmapCompletionToolCall"]


ToolCall_CrossIndexing: typing_extensions.TypeAlias = typing.Union["ListFilesToolCallWithoutProjectName", "DatabaseToolCall", "SearchKeywordToolCallWithoutProjectName", "CompletionToolCall_CrossIndexing"]
